insert into filme(nome,ano ,descricao)
values  ('O Senhor dos Anéis: A Sociedade do Anel', 2001, 'Uma jornada para destruir o anel do poder.'),
('O Poderoso Chefão', 1972, 'A história da família Corleone no crime organizado.'),
('Forrest Gump', 1994, 'A vida de um homem simples que impacta a história dos EUA.'),
('A Origem', 2010, 'Ladrão de ideias invade os sonhos das pessoas.'),
('Matrix', 1999, 'Hacker descobre que a realidade é uma ilusão criada por máquinas.'),
('Jurassic Park', 1993, 'Cientistas tentam controlar dinossauros clonados.'),
('O Rei Leão', 1994, 'Simba luta para se tornar o rei da savana.'),
('Gladiador', 2000, 'General romano busca vingança nas arenas de gladiadores.'),
('Harry Potter e a Pedra Filosofal', 2001, 'Jovem bruxo inicia sua jornada na escola de magia.'),
('Titanic', 1997, 'Romance a bordo do navio que afunda.'),
('Pulp Fiction', 1994, 'Histórias entrelaçadas sobre crime e redenção.'),
('Clube da Luta', 1999, 'Homens fundam um clube secreto para desafiar normas sociais.'),
('Cidadão Kane', 1941, 'A vida e o legado de um magnata da mídia.'),
('A Bela e a Fera', 1991, 'Jovem se apaixona por uma fera encantada.'),
('Vingadores: Ultimato', 2019, 'Heróis enfrentam Thanos para salvar o universo.'),
('O Grande Lebowski', 1998, 'Homem preguiçoso se envolve em uma trama de sequestro.'),
('A Viagem de Chihiro', 2001, 'Menina perdida em um mundo de espíritos e criaturas mágicas.'),
('O Exorcista', 1973, 'Menina possuída luta contra um demônio.'),
('O Silêncio dos Inocentes', 1991, 'Agente do FBI procura ajuda de um serial killer.'),
('Star Wars: O Império Contra-Ataca', 1980, 'Heróis enfrentam as forças do Império em uma guerra galáctica.');
